"""Safe local artifact persistence and explicitly bounded remote resolution."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
import hashlib
from pathlib import Path
import urllib.error
import urllib.parse
import urllib.request
import uuid
from typing import Callable

from .core import ArtifactReference


class ArtifactResolutionStatus(str, Enum):
    AVAILABLE = "available"
    UNAVAILABLE = "unavailable"
    INVALID = "invalid"
    ERROR = "error"


@dataclass(frozen=True)
class ArtifactResolution:
    status: ArtifactResolutionStatus
    reference: ArtifactReference | None
    reason: str


class ArtifactSafetyError(ValueError):
    """Raised when an artifact reference violates the allowed safety policy."""


RemoteFetcher = Callable[[str, float, int], bytes]


class _HTTPSOnlyRedirectHandler(urllib.request.HTTPRedirectHandler):
    """Reject redirects that leave the explicitly supported HTTPS scheme."""

    def redirect_request(self, req, fp, code, msg, headers, newurl):
        _validate_remote_url(newurl)
        return super().redirect_request(req, fp, code, msg, headers, newurl)


class ArtifactStore:
    """Store generated bytes under a controlled root and verify references."""

    def __init__(self, root: str | Path, *, max_bytes: int = 10 * 1024 * 1024, timeout_seconds: float = 10.0) -> None:
        if max_bytes <= 0:
            raise ValueError("max_bytes must be positive")
        if timeout_seconds <= 0:
            raise ValueError("timeout_seconds must be positive")
        self.root = Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)
        self.max_bytes = max_bytes
        self.timeout_seconds = timeout_seconds

    def write_generated(self, content: bytes, *, media_type: str, expected_hash: str | None = None) -> ArtifactResolution:
        if not isinstance(content, bytes):
            raise TypeError("generated artifact content must be bytes")
        if len(content) > self.max_bytes:
            return ArtifactResolution(ArtifactResolutionStatus.INVALID, None, "artifact exceeds the configured size limit")
        digest = _content_hash(content)
        if expected_hash is not None and expected_hash != digest:
            return ArtifactResolution(ArtifactResolutionStatus.INVALID, None, "artifact content hash does not match the expected hash")
        artifact_id = f"artifact-{uuid.uuid4().hex}"
        path = self.root / f"{artifact_id}.bin"
        path.write_bytes(content)
        reference = ArtifactReference(artifact_id, digest, media_type, len(content), path.as_uri(), True)
        return ArtifactResolution(ArtifactResolutionStatus.AVAILABLE, reference, "generated artifact persisted and verified")

    def resolve_local(self, reference: ArtifactReference) -> ArtifactResolution:
        if reference.uri is None:
            return ArtifactResolution(ArtifactResolutionStatus.UNAVAILABLE, None, "artifact reference has no local URI")
        parsed = urllib.parse.urlparse(reference.uri)
        if parsed.scheme != "file" or parsed.netloc not in {"", "localhost"}:
            return ArtifactResolution(ArtifactResolutionStatus.INVALID, None, "local artifact references must use a file URI")
        candidate = Path(urllib.parse.unquote(parsed.path)).resolve()
        try:
            candidate.relative_to(self.root)
        except ValueError:
            return ArtifactResolution(ArtifactResolutionStatus.INVALID, None, "artifact path escapes the generated artifact root")
        if candidate.name != f"{reference.artifact_id}.bin":
            return ArtifactResolution(ArtifactResolutionStatus.INVALID, None, "artifact filename is not a generated artifact identifier")
        if not candidate.exists():
            return ArtifactResolution(ArtifactResolutionStatus.UNAVAILABLE, None, "artifact file is unavailable")
        if not candidate.is_file():
            return ArtifactResolution(ArtifactResolutionStatus.INVALID, None, "artifact reference does not resolve to a file")
        content = candidate.read_bytes()
        if len(content) > self.max_bytes:
            return ArtifactResolution(ArtifactResolutionStatus.INVALID, None, "artifact exceeds the configured size limit")
        if _content_hash(content) != reference.content_hash:
            return ArtifactResolution(ArtifactResolutionStatus.INVALID, None, "artifact content hash does not match the persisted reference")
        return ArtifactResolution(ArtifactResolutionStatus.AVAILABLE, reference, "artifact exists and matches its persisted hash")

    def resolve_remote(
        self,
        url: str,
        *,
        media_type: str,
        expected_hash: str | None = None,
        fetcher: RemoteFetcher | None = None,
    ) -> ArtifactResolution:
        _validate_remote_url(url)
        try:
            content = fetcher(url, self.timeout_seconds, self.max_bytes) if fetcher is not None else _fetch_https(url, self.timeout_seconds, self.max_bytes)
        except TimeoutError:
            return ArtifactResolution(ArtifactResolutionStatus.UNAVAILABLE, None, "remote artifact request timed out")
        except (OSError, urllib.error.URLError):
            return ArtifactResolution(ArtifactResolutionStatus.ERROR, None, "remote artifact request failed")
        return self.write_generated(content, media_type=media_type, expected_hash=expected_hash)


def _content_hash(content: bytes) -> str:
    return f"sha256:{hashlib.sha256(content).hexdigest()}"


def _validate_remote_url(url: str) -> None:
    parsed = urllib.parse.urlparse(url)
    if parsed.scheme != "https" or not parsed.hostname or parsed.username or parsed.password:
        raise ArtifactSafetyError("remote artifact URLs must be credential-free HTTPS URLs")
    if parsed.fragment or ".." in parsed.path.split("/"):
        raise ArtifactSafetyError("remote artifact URL path is not allowed")


def _fetch_https(url: str, timeout_seconds: float, max_bytes: int) -> bytes:
    request = urllib.request.Request(url, method="GET", headers={"Accept": "*/*"})
    opener = urllib.request.build_opener(_HTTPSOnlyRedirectHandler)
    with opener.open(request, timeout=timeout_seconds) as response:
        _validate_remote_url(response.geturl())
        content = response.read(max_bytes + 1)
    if len(content) > max_bytes:
        raise ArtifactSafetyError("remote artifact exceeds the configured size limit")
    return content
